format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[directory]
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = "~"
ahead = "+"
behind = "-"
diverged = "+-"
untracked = "?"
stashed = "*"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
